# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startupGui.ui'
#
# Created: Sun Aug 03 21:37:37 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_start(object):
    def setupUi(self, Dialog_start, username, password, netdrive):
        Dialog_start.setObjectName("Dialog_start")
        Dialog_start.resize(400, 407)
        #Dialog_start.resize(399, 500)#386
        Dialog_start.setFixedSize(400, 407)#386
        icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap("../src/bin/images/labcuro_chromatogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/bin/images/labcuro_chromatogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)        
        
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap("../src/bin/images/labcuro_chromatogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_start.setWindowIcon(icon)
        self.label_5 = QtGui.QLabel(Dialog_start)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 401, 411))
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/bin/images/labcuro_full.png"))
        #self.label_5.setPixmap(QtGui.QPixmap("../../../raw_images/labcuro_full.png"))
        self.label_5.setObjectName("label_5")
        self.groupBox = QtGui.QGroupBox(Dialog_start)
        self.groupBox.setGeometry(QtCore.QRect(25, 135, 351, 251))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(100, 194, 241, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_ok = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_ok.setFont(font)
        self.start_ok.setObjectName("start_ok")
        self.horizontalLayout_2.addWidget(self.start_ok)
        self.start_kill = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_kill.setFont(font)
        self.start_kill.setObjectName("start_kill")
        self.horizontalLayout_2.addWidget(self.start_kill)
        self.password = QtGui.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(100, 91, 231, 31))
        self.password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.password.setText("")
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName("password")
        self.password.setText(password)
        self.username = QtGui.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(100, 55, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setText("")
        self.username.setPlaceholderText("")
        self.username.setObjectName("username")
        self.username.setText(username)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 99, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 171, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 137, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 62, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.powerpassword = QtGui.QLineEdit(self.groupBox)
        self.powerpassword.setGeometry(QtCore.QRect(100, 163, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.powerpassword.setFont(font)
        self.powerpassword.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.powerpassword.setText("")
        self.powerpassword.setEchoMode(QtGui.QLineEdit.Password)
        self.powerpassword.setObjectName("powerpassword")
        self.domain = QtGui.QLineEdit(self.groupBox)
        self.domain.setGeometry(QtCore.QRect(100, 127, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.domain.setFont(font)
        self.domain.setObjectName("domain")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 8, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtGui.QFrame.Panel)
        self.label.setFrameShadow(QtGui.QFrame.Sunken)
        self.label.setMidLineWidth(3)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.LogText)
        self.label.setPixmap(QtGui.QPixmap(":/bin/images/lab_access.png"))
        #self.label.setPixmap(QtGui.QPixmap("../../../raw_images/labcuro_full.png"))
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(14, 8, 321, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setMidLineWidth(3)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_start, netdrive)
        QtCore.QMetaObject.connectSlotsByName(Dialog_start)
        Dialog_start.setTabOrder(self.username, self.password)
        Dialog_start.setTabOrder(self.password, self.domain)
        Dialog_start.setTabOrder(self.domain, self.powerpassword)
        Dialog_start.setTabOrder(self.powerpassword, self.start_ok)
        Dialog_start.setTabOrder(self.start_ok, self.start_kill)

    def retranslateUi(self, Dialog_start, netdrive):
        Dialog_start.setWindowTitle(QtGui.QApplication.translate("Dialog_start", "LabCuro Clinical Suite v2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.start_ok.setText(QtGui.QApplication.translate("Dialog_start", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.start_kill.setText(QtGui.QApplication.translate("Dialog_start", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_start", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_start", "Full access", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_start", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_start", "User name", None, QtGui.QApplication.UnicodeUTF8))
        self.domain.setText(QtGui.QApplication.translate("Dialog_start", "MEDICAL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_start", str("Lab access:  " + netdrive), None, QtGui.QApplication.UnicodeUTF8))

