# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startupGui.ui'
#
# Created: Mon Jun 30 18:30:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_start(object):
    def setupUi(self,  Dialog_start, username):
        Dialog_start.setObjectName("Dialog_start")
        Dialog_start.resize(399, 500)#386
        Dialog_start.setFixedSize(399, 400)#386
        icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap("../src/bin/images/labcuro_chromatogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/bin/images/labcuro_chromatogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_start.setWindowIcon(icon)
        self.label_5 = QtGui.QLabel(Dialog_start)
        self.label_5.setGeometry(QtCore.QRect(0, -30, 501, 461))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/bin/images/labcuro_full.png"))
        #self.label_5.setPixmap(QtGui.QPixmap("../src/bin/images/labcuro_full.png"))
        self.label_5.setObjectName("label_5")
        self.groupBox = QtGui.QGroupBox(Dialog_start)
        self.groupBox.setGeometry(QtCore.QRect(23, 127, 351, 241))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(100, 180, 241, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_ok = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_ok.setFont(font)
        self.start_ok.setObjectName("start_ok")
        self.horizontalLayout_2.addWidget(self.start_ok)
        self.start_kill = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_kill.setFont(font)
        self.start_kill.setObjectName("start_kill")
        self.horizontalLayout_2.addWidget(self.start_kill)
        self.password = QtGui.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(100, 53, 231, 31))
        self.password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        #self.password.setText("g3rcamzul")
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName("password")
        self.username = QtGui.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(100, 13, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setText("")
        self.username.setPlaceholderText("")
        self.username.setObjectName("username")
        self.username.setText(username)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 61, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 143, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 103, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.powerpassword = QtGui.QLineEdit(self.groupBox)
        self.powerpassword.setGeometry(QtCore.QRect(100, 135, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.powerpassword.setFont(font)
        self.powerpassword.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.powerpassword.setText("")
        self.powerpassword.setEchoMode(QtGui.QLineEdit.Password)
        self.powerpassword.setObjectName("powerpassword")
        self.domain = QtGui.QLineEdit(self.groupBox)
        self.domain.setGeometry(QtCore.QRect(100, 93, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.domain.setFont(font)
        self.domain.setObjectName("domain")

        self.retranslateUi(Dialog_start)
        QtCore.QMetaObject.connectSlotsByName(Dialog_start)
        Dialog_start.setTabOrder(self.username, self.password)
        Dialog_start.setTabOrder(self.password, self.domain)
        Dialog_start.setTabOrder(self.domain, self.powerpassword)
        Dialog_start.setTabOrder(self.powerpassword, self.start_ok)
        Dialog_start.setTabOrder(self.start_ok, self.start_kill)

    def retranslateUi(self, Dialog_start):
        Dialog_start.setWindowTitle(QtGui.QApplication.translate("Dialog_start", "LabCuro v2.0 Clinical Suite", None, QtGui.QApplication.UnicodeUTF8))
        self.start_ok.setText(QtGui.QApplication.translate("Dialog_start", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.start_kill.setText(QtGui.QApplication.translate("Dialog_start", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_start", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_start", "Full access", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_start", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_start", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.domain.setText(QtGui.QApplication.translate("Dialog_start", "MEDICAL", None, QtGui.QApplication.UnicodeUTF8))
        ## COMMENT THESE BEFORE DEPLOYMENT
        #self.username.setText(QtGui.QApplication.translate("Dialog_start", 'username', None, QtGui.QApplication.UnicodeUTF8))
        #self.password.setText(QtGui.QApplication.translate("Dialog_start", "g3rcamzul", None, QtGui.QApplication.UnicodeUTF8))
        #self.powerpassword.setText(QtGui.QApplication.translate("Dialog_start", "1haveth3p0w3r", None, QtGui.QApplication.UnicodeUTF8))
        

